// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcEOtLvFElAGV9Cn9OuB_dD35U1sqAEj8',
    appId: '1:552829098749:web:4bb4fc9cb067236c94bc94',
    messagingSenderId: '552829098749',
    projectId: 'flutter-firebase-6f7b1',
    authDomain: 'flutter-firebase-6f7b1.firebaseapp.com',
    storageBucket: 'flutter-firebase-6f7b1.appspot.com',
    measurementId: 'G-S87CMTSB22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6BW0rJBe452HsFHN_02kG2wXBTo6oZEI',
    appId: '1:552829098749:android:9c7bccae5781685194bc94',
    messagingSenderId: '552829098749',
    projectId: 'flutter-firebase-6f7b1',
    storageBucket: 'flutter-firebase-6f7b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd40yr6pl6liE5OrSW4eqEuMvj3RP6d20',
    appId: '1:552829098749:ios:7178c10ccdf4f70794bc94',
    messagingSenderId: '552829098749',
    projectId: 'flutter-firebase-6f7b1',
    storageBucket: 'flutter-firebase-6f7b1.appspot.com',
    iosClientId: '552829098749-557qhtji1t43cgia8tjbthro3h33k7k4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd40yr6pl6liE5OrSW4eqEuMvj3RP6d20',
    appId: '1:552829098749:ios:7178c10ccdf4f70794bc94',
    messagingSenderId: '552829098749',
    projectId: 'flutter-firebase-6f7b1',
    storageBucket: 'flutter-firebase-6f7b1.appspot.com',
    iosClientId: '552829098749-557qhtji1t43cgia8tjbthro3h33k7k4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
